# The optional $5 lifetime ad-free supporter license is bought inside the app:
# Settings -> Privacy -> Supporter.
custom: ['https://github.com/caamer20/Telegram-Drive#optional-5-lifetime-ad-free-supporter-license']
